- name: Installing Nginx
  hosts: web
  become: true
  tasks: 
    - name: install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: start nginx
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes
